# Generated by Django 2.0.5 on 2018-05-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_lmsusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventPoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='lms',
            name='MaxPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lms',
            name='PointsIsOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpoins',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMS'),
        ),
        migrations.AlterUniqueTogether(
            name='eventpoins',
            unique_together={('lms', 'event')},
        ),
    ]
