# Generated by Django 2.0.5 on 2018-05-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180525_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMS')),
            ],
        ),
        migrations.AlterField(
            model_name='eventpoins',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMSEvents'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
