# Generated by Django 2.0.5 on 2018-05-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20180525_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPoins',
            new_name='EventPoints',
        ),
    ]
