# Generated by Django 2.0.5 on 2018-05-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20180527_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lms',
            name='MaxLevel',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lms',
            name='PointPerLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lms',
            name='PointsIsOn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='lmsevents',
            unique_together={('lms', 'name')},
        ),
        migrations.AddField(
            model_name='leveloption',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMSEvents'),
        ),
        migrations.AddField(
            model_name='leveloption',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMS'),
        ),
        migrations.AlterUniqueTogether(
            name='leveloption',
            unique_together={('lms', 'event')},
        ),
    ]
