# Generated by Django 2.0.5 on 2018-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20180527_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms',
            name='MaxLevel',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='lms',
            name='MaxPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lms',
            name='PointPerLevel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lms',
            name='PointsIsOn',
            field=models.BooleanField(default=False),
        ),
    ]
