# Generated by Django 2.0.5 on 2018-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20180527_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveloption',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
