# Generated by Django 2.0.5 on 2018-05-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_leveloption_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
                ('comparison_type', models.IntegerField(default=0)),
                ('criterion', models.IntegerField(default=0)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.LMS')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.LMSEvents', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='badges',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Parameters'),
        ),
    ]
