# Generated by Django 2.0.5 on 2018-05-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20180529_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='lms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.LMS'),
        ),
    ]
