# Generated by Django 2.0.5 on 2018-06-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20180531_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelOption',
            new_name='LevelOptions',
        ),
    ]
